<?php
/**
 * @var \Magento\Payment\Block\Info $block
 * @see \Magento\Payment\Block\Info
 */
$title = $block->escapeHtml($block->getMethod()->getTitle());
$data = $block->getOfflineInfo();

$type = $data["type"];
$info = $data["data"];
$instructions = $block->getInstructions();
?>
<dl class="payment-method">
    <dt class="title"><?php /* @noEscape */ echo $title; ?></dt>
    <dd class="content">
        <p><strong><?php echo __('Instructions:'); ?></strong><br><?php echo $instructions; ?></p>
        <table class="data-table admin__table-secondary">
            <tbody>
                <?php 
                     switch ($type):
                        case "conekta_oxxo": ?>
                        <tr>
                            <td colspan="2" align="center">
                                <img src="<?php echo $info["barcode_url"]; ?>" alt="Barcode Image" />
                            </td>
                        </tr>
                        <tr>
                            <th><strong><?php echo __('Reference Number:'); ?></strong></th>
                            <td>
                                <?php echo $info["barcode"]; ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                            <th><strong><?php echo __('Expires at:'); ?></strong></th>
                                <?php echo date("Y-m-d", (integer) $info["expires_at"]); ?>
                            </td>
                        </tr>
                <?php
                     break;
                        case "conekta_banorte": ?>
                        <tr>
                            <th><strong><?php echo __('Reference Number:'); ?></strong></th>
                            <td><?php echo $info["reference"]; ?></td>
                        </tr>
                        <tr>
                            <th><strong><?php echo __('Service Number:'); ?></strong></th>
                            <td><?php echo $info["service_number"]; ?></td>
                        </tr>
                        <tr>
                            <th><strong><?php echo __('Service Name:'); ?></strong></th>
                            <td><br><?php echo $info["service_name"]; ?></td>
                        </tr>
                        <tr>
                            <th><strong><?php echo __('Expires at:'); ?></strong></th>
                            <td><?php echo date("Y-m-d", (integer) $info["expires_at"]); ?></td>
                        </tr>
                <?php
                     break;
                    endswitch; ?>
            </tbody>
        </table>
    </dd>
</dl>
<?php echo $block->getChildHtml(); ?>