<?php /** @var $block \Conekta\Oxxo\Block\Success */ ?>
<div class="checkout-success">
    <?php if ($block->getOrderId()):?>
        <?php if ($block->getCanViewOrder()): ?>
            <p><?php echo __('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
        <?php else: ?>
            <p><?php echo __('Your order # is: <span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?></p>
        <?php endif; ?>

        <!-- BEGIN VENDOR_MODULE CUSTOM -->
        <p><?php echo __('You ordered %1 items.', (int) $block->getOrder()->getTotalQtyOrdered()) ?></p>
        <!-- END VENDOR_MODULE CUSTOM -->
        
        <?php if (in_array($block->getMethod(), ["conekta_oxxo"])): ?>
            <p>
                <h5><?php echo __('Instructions:'); ?></h5>
                <?php echo __($block->getInstructions()); ?>
            </p>

            <table class="data">
                <tbody>
                    <tr>
                        <td><img src="<?php echo $block->getBarcode()->barcode_url; ?>" alt="Barcode Image" /></td>
                    </tr>
                    <tr>
                        <td><strong><?php echo __('Reference Number:'); ?></strong><br><?php echo $block->getBarcode()->barcode; ?></td>
                    </tr>
                    <tr>
                        <td><strong><?php echo __('Expires at:'); ?></strong><br><?php echo date("Y-m-d", (integer) $block->getBarcode()->expires_at); ?></td>
                    </tr>
                </tbody>
            </table>
        <?php endif; ?>
        <p><?php /* @escapeNotVerified */ echo __('We\'ll email you an order confirmation with details and tracking info.') ?></p>
    <?php endif; ?>

    <?php echo $block->getAdditionalInfoHtml() ?>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?php /* @escapeNotVerified */ echo $block->getUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span></a>
        </div>
    </div>
</div>